"""upgrading order with address

Revision ID: 09aeba276be9
Revises: f35a4baf2ec9
Create Date: 2026-08-01 13:33:24.125180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09aeba276be9'
down_revision: Union[str, Sequence[str], None] = 'f35a4baf2ec9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('address_id', sa.Integer(), nullable=True))
    op.alter_column('orders', 'customer_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.drop_index(op.f('ix_orders_customer_id'), table_name='orders')
    op.create_foreign_key(None, 'orders', 'order_addresses', ['address_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.create_index(op.f('ix_orders_customer_id'), 'orders', ['customer_id'], unique=False)
    op.alter_column('orders', 'customer_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.drop_column('orders', 'address_id')
    # ### end Alembic commands ###
