"""addig user id to Cart Table

Revision ID: 0ce3ef33bea1
Revises: 9553b9df929d
Create Date: 2026-07-14 20:13:55.323750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ce3ef33bea1'
down_revision: Union[str, Sequence[str], None] = '9553b9df929d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart_items', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('cart_items', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('cart_items', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('carts', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('carts', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'carts', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'carts', type_='foreignkey')
    op.drop_column('carts', 'deleted_at')
    op.drop_column('carts', 'user_id')
    op.drop_column('cart_items', 'updated_at')
    op.drop_column('cart_items', 'deleted_at')
    op.drop_column('cart_items', 'created_at')
    # ### end Alembic commands ###
