"""is_active column change to status

Revision ID: 3ce0bedde7b3
Revises: 676b6f397bfb
Create Date: 2026-07-15 20:38:06.485725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ce0bedde7b3'
down_revision: Union[str, Sequence[str], None] = '676b6f397bfb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('brands', sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='status', native_enum=False), server_default=sa.text("'active'"), nullable=False))
    op.drop_column('brands', 'is_active')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('brands', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('brands', 'status')
    # ### end Alembic commands ###
