"""added coupon id in PromotionUsage

Revision ID: 69ff785253e6
Revises: 0ce3ef33bea1
Create Date: 2026-07-14 22:40:00.452288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69ff785253e6'
down_revision: Union[str, Sequence[str], None] = '0ce3ef33bea1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'discount')
    op.add_column('promotion_usages', sa.Column('promotion_coupon_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('promotion_usages_user_id_fkey'), 'promotion_usages', type_='foreignkey')
    op.drop_constraint(op.f('promotion_usages_order_id_fkey'), 'promotion_usages', type_='foreignkey')
    op.drop_constraint(op.f('promotion_usages_promotion_id_fkey'), 'promotion_usages', type_='foreignkey')
    op.create_foreign_key(None, 'promotion_usages', 'promotion_coupons', ['promotion_coupon_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'promotion_usages', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'promotion_usages', 'promotions', ['promotion_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'promotion_usages', 'orders', ['order_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'promotion_usages', type_='foreignkey')
    op.drop_constraint(None, 'promotion_usages', type_='foreignkey')
    op.drop_constraint(None, 'promotion_usages', type_='foreignkey')
    op.drop_constraint(None, 'promotion_usages', type_='foreignkey')
    op.create_foreign_key(op.f('promotion_usages_promotion_id_fkey'), 'promotion_usages', 'promotions', ['promotion_id'], ['id'])
    op.create_foreign_key(op.f('promotion_usages_order_id_fkey'), 'promotion_usages', 'orders', ['order_id'], ['id'])
    op.create_foreign_key(op.f('promotion_usages_user_id_fkey'), 'promotion_usages', 'users', ['user_id'], ['id'])
    op.drop_column('promotion_usages', 'promotion_coupon_id')
    op.add_column('orders', sa.Column('discount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
