"""change color_name to name of ProductVariant

Revision ID: 9553b9df929d
Revises: d829473f64f9
Create Date: 2026-07-14 14:56:10.414526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9553b9df929d'
down_revision: Union[str, Sequence[str], None] = 'd829473f64f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_variants', sa.Column('name', sa.String(length=100), nullable=True))
    op.drop_column('product_variants', 'color_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_variants', sa.Column('color_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('product_variants', 'name')
    # ### end Alembic commands ###
