"""is_active columns to status of category

Revision ID: bf70ea6be6f6
Revises: e37476b0d108
Create Date: 2026-07-16 13:00:39.759345

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf70ea6be6f6'
down_revision: Union[str, Sequence[str], None] = 'e37476b0d108'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='status', native_enum=False), server_default=sa.text("'active'"), nullable=False))
    op.drop_column('categories', 'is_active')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('categories', 'status')
    # ### end Alembic commands ###
