"""change brand to brand_id of product

Revision ID: e37476b0d108
Revises: 3ce0bedde7b3
Create Date: 2026-07-16 11:13:07.213049

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e37476b0d108'
down_revision: Union[str, Sequence[str], None] = '3ce0bedde7b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('brand_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('products_brand_fkey'), 'products', type_='foreignkey')
    op.create_foreign_key(None, 'products', 'brands', ['brand_id'], ['id'])
    op.drop_column('products', 'brand')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('brand', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.create_foreign_key(op.f('products_brand_fkey'), 'products', 'brands', ['brand'], ['id'])
    op.drop_column('products', 'brand_id')
    # ### end Alembic commands ###
