"""initial schema

Revision ID: f35a4baf2ec9
Revises: 
Create Date: 2026-08-01 12:28:04.882436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f35a4baf2ec9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('badges',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_badges_id'), 'badges', ['id'], unique=False)
    op.create_table('brands',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('logo_url', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='status', native_enum=False), server_default=sa.text("'active'"), nullable=False),
    sa.Column('website_url', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_brands_id'), 'brands', ['id'], unique=False)
    op.create_table('categories',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='status', native_enum=False), server_default=sa.text("'active'"), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('logo_url', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_categories_id'), 'categories', ['id'], unique=False)
    op.create_table('promotion_types',
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('is_active', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_promotion_types_id'), 'promotion_types', ['id'], unique=False)
    op.create_table('shipping_zones',
    sa.Column('zone_code', sa.String(length=30), nullable=False),
    sa.Column('zone_name', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shipping_zones_id'), 'shipping_zones', ['id'], unique=False)
    op.create_index(op.f('ix_shipping_zones_zone_code'), 'shipping_zones', ['zone_code'], unique=True)
    op.create_index(op.f('ix_shipping_zones_zone_name'), 'shipping_zones', ['zone_name'], unique=False)
    op.create_table('tags',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tags_id'), 'tags', ['id'], unique=False)
    op.create_table('users',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('dob', sa.DateTime(), nullable=False),
    sa.Column('mobile', sa.String(length=20), nullable=False),
    sa.Column('gender', sa.String(length=20), nullable=False),
    sa.Column('role', sa.Enum('USER', 'ADMIN', name='userrole'), nullable=False),
    sa.Column('user_type', sa.Enum('RETAIL', 'WHOLESALE', 'CORPORATE', 'VIP', 'EMPLOYEE', name='customer_group_type', native_enum=False), server_default='RETAIL', nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('warehouses',
    sa.Column('warehouse_code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('contact_person', sa.String(length=150), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('address_line1', sa.String(length=255), nullable=False),
    sa.Column('address_line2', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'MAINTENANCE', 'CLOSED', name='warehouse_status', native_enum=False), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_warehouses_id'), 'warehouses', ['id'], unique=False)
    op.create_index(op.f('ix_warehouses_warehouse_code'), 'warehouses', ['warehouse_code'], unique=True)
    op.create_table('carts',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('owner_type', sa.String(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_carts_id'), 'carts', ['id'], unique=False)
    op.create_table('order_addresses',
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('thana', sa.String(length=100), nullable=True),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.Column('landmark', sa.String(length=300), nullable=True),
    sa.Column('recipient_name', sa.String(length=100), nullable=True),
    sa.Column('recipient_contact', sa.String(length=20), nullable=True),
    sa.Column('recipient_backup_contact', sa.String(length=20), nullable=True),
    sa.Column('recipient_email', sa.String(length=100), nullable=True),
    sa.Column('address_category', sa.Enum('Home', 'office', name='addresscategory'), nullable=True),
    sa.Column('default_shipping_address', sa.Enum('on', 'off', name='defaultshippingaddress'), nullable=True),
    sa.Column('default_billing_address', sa.Enum('on', 'off', name='defaultbillingaddress'), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_addresses_id'), 'order_addresses', ['id'], unique=False)
    op.create_table('orders',
    sa.Column('customer_id', sa.BigInteger(), nullable=False),
    sa.Column('order_number', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'PROCESSING', 'ON_HOLD', 'PARTIALLY_FULFILLED', 'COMPLETED', 'CANCELLED', 'RETURN_REQUESTED', 'RETURNED', 'PARTIALLY_RETURNED', 'REFUNDED', 'PARTIALLY_REFUNDED', name='order_status', native_enum=False), nullable=False),
    sa.Column('fulfillment_status', sa.Enum('PENDING', 'PROCESSING', 'PACKED', 'SHIPPED', 'DELIVERED', name='fullfillment_status', native_enum=False), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('discount_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('shipping_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tax_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('grand_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('coupon_code', sa.String(length=100), nullable=True),
    sa.Column('customer_note', sa.Text(), nullable=True),
    sa.Column('admin_note', sa.Text(), nullable=True),
    sa.Column('is_guest_order', sa.Boolean(), nullable=False),
    sa.Column('placed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('shipped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_customer_id'), 'orders', ['customer_id'], unique=False)
    op.create_index(op.f('ix_orders_fulfillment_status'), 'orders', ['fulfillment_status'], unique=False)
    op.create_index(op.f('ix_orders_id'), 'orders', ['id'], unique=False)
    op.create_index(op.f('ix_orders_order_number'), 'orders', ['order_number'], unique=True)
    op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
    op.create_table('products',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('category', sa.Integer(), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=255), nullable=True),
    sa.Column('search_boost', sa.Integer(), nullable=True),
    sa.Column('min_price', sa.Float(), nullable=True),
    sa.Column('max_price', sa.Float(), nullable=True),
    sa.Column('slug', sa.String(length=255), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('product_code', sa.String(length=100), nullable=True),
    sa.Column('brand_id', sa.Integer(), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('short_description', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.ForeignKeyConstraint(['category'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_code'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    op.create_table('promotions',
    sa.Column('promotion_type_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'scheduled', 'active', 'paused', 'expired', 'archived', name='promotion_status_enum', native_enum=False), server_default='draft', nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('stackable', sa.Boolean(), nullable=False),
    sa.Column('usage_limit', sa.Integer(), nullable=True),
    sa.Column('usage_per_customer', sa.Integer(), nullable=True),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('coupon_required', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['promotion_type_id'], ['promotion_types.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_promotions_code'), 'promotions', ['code'], unique=True)
    op.create_index(op.f('ix_promotions_id'), 'promotions', ['id'], unique=False)
    op.create_index(op.f('ix_promotions_status'), 'promotions', ['status'], unique=False)
    op.create_table('shipping_rates',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('shipping_method', sa.String(length=50), nullable=False),
    sa.Column('carrier', sa.String(length=100), nullable=True),
    sa.Column('service_level', sa.String(length=50), nullable=True),
    sa.Column('zone_id', sa.Integer(), nullable=True),
    sa.Column('minimum_order_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('maximum_order_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('minimum_weight', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('maximum_weight', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('base_rate', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('additional_rate_per_kg', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('free_shipping', sa.Boolean(), nullable=False),
    sa.Column('estimated_delivery_days', sa.Integer(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['zone_id'], ['shipping_zones.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shipping_rates_carrier'), 'shipping_rates', ['carrier'], unique=False)
    op.create_index(op.f('ix_shipping_rates_id'), 'shipping_rates', ['id'], unique=False)
    op.create_index(op.f('ix_shipping_rates_name'), 'shipping_rates', ['name'], unique=True)
    op.create_index(op.f('ix_shipping_rates_shipping_method'), 'shipping_rates', ['shipping_method'], unique=False)
    op.create_index(op.f('ix_shipping_rates_zone_id'), 'shipping_rates', ['zone_id'], unique=False)
    op.create_table('user_sessions',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('refresh_token', sa.Text(), nullable=False),
    sa.Column('device_name', sa.String(length=100), nullable=False),
    sa.Column('device_type', sa.String(length=50), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('user_agent', sa.Text(), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_sessions_id'), 'user_sessions', ['id'], unique=False)
    op.create_table('cart_items',
    sa.Column('cart_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cart_id'], ['carts.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cart_items_id'), 'cart_items', ['id'], unique=False)
    op.create_table('compare_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('delivery_details',
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.Enum('INSIDE_DHAKA', 'OUTSIDE_DHAKA', name='delivery_type', native_enum=False), nullable=False),
    sa.Column('address', sa.Integer(), nullable=True),
    sa.Column('courier', sa.String(), nullable=True),
    sa.Column('tracking_id', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['address'], ['order_addresses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id')
    )
    op.create_index(op.f('ix_delivery_details_id'), 'delivery_details', ['id'], unique=False)
    op.create_table('descriptions',
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_descriptions_id'), 'descriptions', ['id'], unique=False)
    op.create_table('inventory_summaries',
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('available', sa.Integer(), nullable=True),
    sa.Column('reserved', sa.Integer(), nullable=True),
    sa.Column('incoming', sa.Integer(), nullable=True),
    sa.Column('low_stock_threshold', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_summaries_id'), 'inventory_summaries', ['id'], unique=False)
    op.create_table('invoices',
    sa.Column('order_id', sa.BigInteger(), nullable=False),
    sa.Column('invoice_number', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('discount_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('shipping_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tax_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('grand_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('paid_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('due_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('pdf_url', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoices_id'), 'invoices', ['id'], unique=False)
    op.create_index(op.f('ix_invoices_invoice_number'), 'invoices', ['invoice_number'], unique=True)
    op.create_index(op.f('ix_invoices_order_id'), 'invoices', ['order_id'], unique=True)
    op.create_index(op.f('ix_invoices_status'), 'invoices', ['status'], unique=False)
    op.create_table('order_discounts',
    sa.Column('order_id', sa.BigInteger(), nullable=False),
    sa.Column('promotion_id', sa.BigInteger(), nullable=True),
    sa.Column('coupon_code', sa.String(length=100), nullable=True),
    sa.Column('discount_name', sa.String(length=255), nullable=False),
    sa.Column('discount_type', sa.String(length=50), nullable=False),
    sa.Column('discount_value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['promotion_id'], ['promotions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_discounts_coupon_code'), 'order_discounts', ['coupon_code'], unique=False)
    op.create_index(op.f('ix_order_discounts_id'), 'order_discounts', ['id'], unique=False)
    op.create_index(op.f('ix_order_discounts_order_id'), 'order_discounts', ['order_id'], unique=False)
    op.create_index(op.f('ix_order_discounts_promotion_id'), 'order_discounts', ['promotion_id'], unique=False)
    op.create_table('order_items',
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('variant_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('sku', sa.String(), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_items_id'), 'order_items', ['id'], unique=False)
    op.create_table('order_notes',
    sa.Column('order_id', sa.BigInteger(), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('note_type', sa.String(length=30), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('is_customer_visible', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_notes_created_by'), 'order_notes', ['created_by'], unique=False)
    op.create_index(op.f('ix_order_notes_id'), 'order_notes', ['id'], unique=False)
    op.create_index(op.f('ix_order_notes_note_type'), 'order_notes', ['note_type'], unique=False)
    op.create_index(op.f('ix_order_notes_order_id'), 'order_notes', ['order_id'], unique=False)
    op.create_table('order_notifications',
    sa.Column('order_id', sa.BigInteger(), nullable=False),
    sa.Column('notification_type', sa.String(length=30), nullable=False),
    sa.Column('recipient', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('provider', sa.String(length=100), nullable=True),
    sa.Column('provider_message_id', sa.String(length=255), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_message_id')
    )
    op.create_index(op.f('ix_order_notifications_id'), 'order_notifications', ['id'], unique=False)
    op.create_index(op.f('ix_order_notifications_notification_type'), 'order_notifications', ['notification_type'], unique=False)
    op.create_index(op.f('ix_order_notifications_order_id'), 'order_notifications', ['order_id'], unique=False)
    op.create_index(op.f('ix_order_notifications_status'), 'order_notifications', ['status'], unique=False)
    op.create_table('order_timelines',
    sa.Column('order_id', sa.BigInteger(), nullable=False),
    sa.Column('event', sa.String(length=100), nullable=False),
    sa.Column('previous_status', sa.String(length=50), nullable=True),
    sa.Column('current_status', sa.String(length=50), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('actor_type', sa.String(length=30), nullable=False),
    sa.Column('actor_id', sa.BigInteger(), nullable=True),
    sa.Column('actor_name', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('metadata_', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_timelines_event'), 'order_timelines', ['event'], unique=False)
    op.create_index(op.f('ix_order_timelines_id'), 'order_timelines', ['id'], unique=False)
    op.create_index(op.f('ix_order_timelines_order_id'), 'order_timelines', ['order_id'], unique=False)
    op.create_table('payments',
    sa.Column('order_id', sa.BigInteger(), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=False),
    sa.Column('payment_provider', sa.String(length=50), nullable=False),
    sa.Column('payment_status', sa.Enum('PENDING', 'AUTHORIZED', 'PAID', 'PARTIALLY_PAID', 'FAILED', 'CANCELLED', 'REFUNDED', 'PARTIALLY_REFUNDED', name='payment_status', native_enum=False), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('exchange_rate', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('paid_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('due_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('refunded_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('gateway_reference', sa.String(length=255), nullable=True),
    sa.Column('gateway_order_id', sa.String(length=255), nullable=True),
    sa.Column('payment_url', sa.Text(), nullable=True),
    sa.Column('is_test', sa.Boolean(), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_id'), 'payments', ['id'], unique=False)
    op.create_index(op.f('ix_payments_order_id'), 'payments', ['order_id'], unique=False)
    op.create_index(op.f('ix_payments_payment_method'), 'payments', ['payment_method'], unique=False)
    op.create_index(op.f('ix_payments_payment_provider'), 'payments', ['payment_provider'], unique=False)
    op.create_table('product_badges',
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('badge_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['badge_id'], ['badges.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_badges_id'), 'product_badges', ['id'], unique=False)
    op.create_table('product_seo',
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('meta_title', sa.String(length=255), nullable=True),
    sa.Column('meta_description', sa.Text(), nullable=True),
    sa.Column('canonical_url', sa.String(length=255), nullable=True),
    sa.Column('og_image', sa.String(length=255), nullable=True),
    sa.Column('no_index', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_seo_id'), 'product_seo', ['id'], unique=False)
    op.create_table('product_tags',
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_tags_id'), 'product_tags', ['id'], unique=False)
    op.create_table('product_variants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('compare_at_price', sa.Float(), nullable=True),
    sa.Column('inventory', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('weight', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('sku', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sku')
    )
    op.create_table('product_videos',
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('video_url', sa.String(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('platform', sa.String(length=50), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_videos_id'), 'product_videos', ['id'], unique=False)
    op.create_table('promotion_actions',
    sa.Column('promotion_id', sa.Integer(), nullable=False, comment='Parent promotion'),
    sa.Column('reward_type', sa.Enum('percentage', 'fixed_amount', 'free_shipping', 'free_product', 'buy_x_get_y', 'gift_product', 'bundle_price', 'loyalty_points', 'cashback', name='reward_type_enum', native_enum=False), nullable=False, comment='Type of reward'),
    sa.Column('action_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Reward configuration in JSON format'),
    sa.Column('sort_order', sa.Integer(), server_default='1', nullable=False, comment='Execution order if multiple actions exist'),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['promotion_id'], ['promotions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_promotion_action_promotion', 'promotion_actions', ['promotion_id'], unique=False)
    op.create_index('ix_promotion_action_reward_type', 'promotion_actions', ['reward_type'], unique=False)
    op.create_index(op.f('ix_promotion_actions_id'), 'promotion_actions', ['id'], unique=False)
    op.create_table('promotion_coupons',
    sa.Column('promotion_id', sa.Integer(), nullable=False, comment='Promotion that owns this coupon.'),
    sa.Column('code', sa.String(length=100), nullable=False, comment='Coupon code entered by customer.'),
    sa.Column('status', sa.Enum('active', 'inactive', 'expired', 'disabled', name='coupon_status_enum', native_enum=False), server_default='active', nullable=False),
    sa.Column('usage_limit', sa.Integer(), nullable=True, comment='Maximum number of times this coupon can be used.'),
    sa.Column('usage_limit_per_customer', sa.Integer(), nullable=True, comment='Maximum number of uses per customer.'),
    sa.Column('current_usage', sa.Integer(), server_default='0', nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=True, comment='Coupon activation time.'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True, comment='Coupon expiration time.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['promotion_id'], ['promotions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index('ix_promotion_coupon_code', 'promotion_coupons', ['code'], unique=False)
    op.create_index('ix_promotion_coupon_promotion', 'promotion_coupons', ['promotion_id'], unique=False)
    op.create_index('ix_promotion_coupon_status', 'promotion_coupons', ['status'], unique=False)
    op.create_index(op.f('ix_promotion_coupons_id'), 'promotion_coupons', ['id'], unique=False)
    op.create_table('promotion_rules',
    sa.Column('promotion_id', sa.Integer(), nullable=False),
    sa.Column('rule_type', sa.Enum('minimum_order_amount', 'minimum_quantity', 'maximum_quantity', 'customer_group', 'customer', 'brand', 'category', 'collection', 'product', 'variant', 'payment_method', 'shipping_zone', 'shipping_country', 'first_order', 'customer_total_spent', 'customer_order_count', 'weekday', 'time_range', name='rule_type', native_enum=False), nullable=False),
    sa.Column('operator', sa.Enum('eq', 'ne', 'gt', 'gte', 'lt', 'lte', 'in', 'not_in', 'contains', 'not_contains', 'starts_with', 'ends_with', 'between', 'is_true', 'is_false', name='rule_operator', native_enum=False), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('logical_group', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['promotion_id'], ['promotions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_promotion_rules_id'), 'promotion_rules', ['id'], unique=False)
    op.create_index(op.f('ix_promotion_rules_promotion_id'), 'promotion_rules', ['promotion_id'], unique=False)
    op.create_table('promotion_targets',
    sa.Column('promotion_id', sa.Integer(), nullable=False),
    sa.Column('target_type', sa.Enum('order', 'product', 'variant', 'category', 'brand', 'collection', 'vendor', 'customer', 'customer_group', 'shipping_zone', 'warehouse', name='promotion_target_type', native_enum=False), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('target_role', sa.Enum('PRODUCT', 'CATEGORY', 'BRAND', 'CUSTOMER_SEGMENT', 'ALL', name='target_role', native_enum=False), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['promotion_id'], ['promotions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_promotion_targets_id'), 'promotion_targets', ['id'], unique=False)
    op.create_index(op.f('ix_promotion_targets_promotion_id'), 'promotion_targets', ['promotion_id'], unique=False)
    op.create_table('questions',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('question', sa.Text(), nullable=True),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_questions_id'), 'questions', ['id'], unique=False)
    op.create_table('related_products',
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('related_product_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['related_product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_related_products_id'), 'related_products', ['id'], unique=False)
    op.create_table('return_requests',
    sa.Column('return_number', sa.String(length=50), nullable=False),
    sa.Column('order_id', sa.BigInteger(), nullable=False),
    sa.Column('customer_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('customer_comment', sa.Text(), nullable=True),
    sa.Column('admin_comment', sa.Text(), nullable=True),
    sa.Column('requested_refund_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('approved_refund_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_closed', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_return_requests_customer_id'), 'return_requests', ['customer_id'], unique=False)
    op.create_index(op.f('ix_return_requests_id'), 'return_requests', ['id'], unique=False)
    op.create_index(op.f('ix_return_requests_order_id'), 'return_requests', ['order_id'], unique=False)
    op.create_index(op.f('ix_return_requests_return_number'), 'return_requests', ['return_number'], unique=True)
    op.create_index(op.f('ix_return_requests_status'), 'return_requests', ['status'], unique=False)
    op.create_table('reviews',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('star', sa.Integer(), nullable=True),
    sa.Column('review', sa.Text(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reviews_id'), 'reviews', ['id'], unique=False)
    op.create_table('search_keywords',
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('keyword', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_search_keywords_id'), 'search_keywords', ['id'], unique=False)
    op.create_table('seo_keywords',
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('keyword', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_seo_keywords_id'), 'seo_keywords', ['id'], unique=False)
    op.create_table('shipments',
    sa.Column('order_id', sa.BigInteger(), nullable=False),
    sa.Column('shipment_number', sa.String(length=50), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=True),
    sa.Column('carrier', sa.String(length=100), nullable=False),
    sa.Column('shipping_service', sa.String(length=100), nullable=True),
    sa.Column('tracking_number', sa.String(length=255), nullable=True),
    sa.Column('tracking_url', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('shipping_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('estimated_delivery_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('shipped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('returned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivery_attempts', sa.BigInteger(), nullable=False),
    sa.Column('is_return_shipment', sa.Boolean(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shipments_carrier'), 'shipments', ['carrier'], unique=False)
    op.create_index(op.f('ix_shipments_id'), 'shipments', ['id'], unique=False)
    op.create_index(op.f('ix_shipments_order_id'), 'shipments', ['order_id'], unique=False)
    op.create_index(op.f('ix_shipments_shipment_number'), 'shipments', ['shipment_number'], unique=True)
    op.create_index(op.f('ix_shipments_status'), 'shipments', ['status'], unique=False)
    op.create_index(op.f('ix_shipments_tracking_number'), 'shipments', ['tracking_number'], unique=True)
    op.create_index(op.f('ix_shipments_warehouse_id'), 'shipments', ['warehouse_id'], unique=False)
    op.create_table('specification_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_specification_types_id'), 'specification_types', ['id'], unique=False)
    op.create_table('image_group',
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('group_type', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('variant_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_image_group_id'), 'image_group', ['id'], unique=False)
    op.create_table('inventory_reservations',
    sa.Column('order_id', sa.BigInteger(), nullable=False),
    sa.Column('order_item_id', sa.BigInteger(), nullable=False),
    sa.Column('product_variant_id', sa.BigInteger(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('reservation_status', sa.String(length=30), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('released_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_item_id'], ['order_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_variant_id'], ['product_variants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_reservations_id'), 'inventory_reservations', ['id'], unique=False)
    op.create_index(op.f('ix_inventory_reservations_order_id'), 'inventory_reservations', ['order_id'], unique=False)
    op.create_index(op.f('ix_inventory_reservations_order_item_id'), 'inventory_reservations', ['order_item_id'], unique=False)
    op.create_index(op.f('ix_inventory_reservations_product_variant_id'), 'inventory_reservations', ['product_variant_id'], unique=False)
    op.create_index(op.f('ix_inventory_reservations_reservation_status'), 'inventory_reservations', ['reservation_status'], unique=False)
    op.create_table('order_allocations',
    sa.Column('order_item_id', sa.BigInteger(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('allocated_quantity', sa.Integer(), nullable=False),
    sa.Column('picked_quantity', sa.Integer(), nullable=False),
    sa.Column('packed_quantity', sa.Integer(), nullable=False),
    sa.Column('shipped_quantity', sa.Integer(), nullable=False),
    sa.Column('allocation_status', sa.String(length=30), nullable=False),
    sa.Column('allocated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['order_item_id'], ['order_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_allocations_allocation_status'), 'order_allocations', ['allocation_status'], unique=False)
    op.create_index(op.f('ix_order_allocations_id'), 'order_allocations', ['id'], unique=False)
    op.create_index(op.f('ix_order_allocations_order_item_id'), 'order_allocations', ['order_item_id'], unique=False)
    op.create_index(op.f('ix_order_allocations_warehouse_id'), 'order_allocations', ['warehouse_id'], unique=False)
    op.create_table('order_item_discounts',
    sa.Column('order_item_id', sa.BigInteger(), nullable=False),
    sa.Column('promotion_id', sa.BigInteger(), nullable=True),
    sa.Column('discount_name', sa.String(length=255), nullable=False),
    sa.Column('discount_type', sa.String(length=50), nullable=False),
    sa.Column('discount_value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['order_item_id'], ['order_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['promotion_id'], ['promotions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_item_discounts_id'), 'order_item_discounts', ['id'], unique=False)
    op.create_index(op.f('ix_order_item_discounts_order_item_id'), 'order_item_discounts', ['order_item_id'], unique=False)
    op.create_index(op.f('ix_order_item_discounts_promotion_id'), 'order_item_discounts', ['promotion_id'], unique=False)
    op.create_table('payment_transactions',
    sa.Column('payment_id', sa.BigInteger(), nullable=False),
    sa.Column('transaction_type', sa.String(length=50), nullable=False),
    sa.Column('transaction_status', sa.String(length=30), nullable=False),
    sa.Column('gateway_transaction_id', sa.String(length=255), nullable=True),
    sa.Column('gateway_reference', sa.String(length=255), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('gateway_response', sa.JSON(), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gateway_transaction_id')
    )
    op.create_index(op.f('ix_payment_transactions_id'), 'payment_transactions', ['id'], unique=False)
    op.create_index(op.f('ix_payment_transactions_payment_id'), 'payment_transactions', ['payment_id'], unique=False)
    op.create_index(op.f('ix_payment_transactions_transaction_status'), 'payment_transactions', ['transaction_status'], unique=False)
    op.create_index(op.f('ix_payment_transactions_transaction_type'), 'payment_transactions', ['transaction_type'], unique=False)
    op.create_table('promotion_usages',
    sa.Column('promotion_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('promotion_coupon_id', sa.Integer(), nullable=True),
    sa.Column('discount_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['promotion_coupon_id'], ['promotion_coupons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['promotion_id'], ['promotions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_promotion_usages_id'), 'promotion_usages', ['id'], unique=False)
    op.create_index(op.f('ix_promotion_usages_order_id'), 'promotion_usages', ['order_id'], unique=False)
    op.create_index(op.f('ix_promotion_usages_promotion_id'), 'promotion_usages', ['promotion_id'], unique=False)
    op.create_index(op.f('ix_promotion_usages_user_id'), 'promotion_usages', ['user_id'], unique=False)
    op.create_table('refunds',
    sa.Column('refund_number', sa.String(length=50), nullable=False),
    sa.Column('payment_id', sa.BigInteger(), nullable=False),
    sa.Column('return_request_id', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('refund_method', sa.String(length=50), nullable=False),
    sa.Column('gateway_refund_id', sa.String(length=255), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['return_request_id'], ['return_requests.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gateway_refund_id')
    )
    op.create_index(op.f('ix_refunds_id'), 'refunds', ['id'], unique=False)
    op.create_index(op.f('ix_refunds_payment_id'), 'refunds', ['payment_id'], unique=False)
    op.create_index(op.f('ix_refunds_refund_number'), 'refunds', ['refund_number'], unique=True)
    op.create_index(op.f('ix_refunds_return_request_id'), 'refunds', ['return_request_id'], unique=False)
    op.create_index(op.f('ix_refunds_status'), 'refunds', ['status'], unique=False)
    op.create_table('return_items',
    sa.Column('return_request_id', sa.BigInteger(), nullable=False),
    sa.Column('order_item_id', sa.BigInteger(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('condition', sa.String(length=100), nullable=True),
    sa.Column('resolution', sa.String(length=50), nullable=True),
    sa.Column('refund_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('customer_note', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['order_item_id'], ['order_items.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['return_request_id'], ['return_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_return_items_id'), 'return_items', ['id'], unique=False)
    op.create_index(op.f('ix_return_items_order_item_id'), 'return_items', ['order_item_id'], unique=False)
    op.create_index(op.f('ix_return_items_return_request_id'), 'return_items', ['return_request_id'], unique=False)
    op.create_table('shipment_items',
    sa.Column('shipment_id', sa.BigInteger(), nullable=False),
    sa.Column('order_item_id', sa.BigInteger(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['order_item_id'], ['order_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shipment_items_id'), 'shipment_items', ['id'], unique=False)
    op.create_index(op.f('ix_shipment_items_order_item_id'), 'shipment_items', ['order_item_id'], unique=False)
    op.create_index(op.f('ix_shipment_items_shipment_id'), 'shipment_items', ['shipment_id'], unique=False)
    op.create_table('specification_values',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.Column('specification_type_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['specification_type_id'], ['specification_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_specification_values_id'), 'specification_values', ['id'], unique=False)
    op.create_table('variant_attributes',
    sa.Column('key', sa.String(), nullable=True),
    sa.Column('value', sa.String(), nullable=True),
    sa.Column('variant_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_variant_attributes_id'), 'variant_attributes', ['id'], unique=False)
    op.create_table('images',
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('alt_text', sa.String(length=255), nullable=True),
    sa.Column('format', sa.String(length=50), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['image_group.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_images_id'), 'images', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_images_id'), table_name='images')
    op.drop_table('images')
    op.drop_index(op.f('ix_variant_attributes_id'), table_name='variant_attributes')
    op.drop_table('variant_attributes')
    op.drop_index(op.f('ix_specification_values_id'), table_name='specification_values')
    op.drop_table('specification_values')
    op.drop_index(op.f('ix_shipment_items_shipment_id'), table_name='shipment_items')
    op.drop_index(op.f('ix_shipment_items_order_item_id'), table_name='shipment_items')
    op.drop_index(op.f('ix_shipment_items_id'), table_name='shipment_items')
    op.drop_table('shipment_items')
    op.drop_index(op.f('ix_return_items_return_request_id'), table_name='return_items')
    op.drop_index(op.f('ix_return_items_order_item_id'), table_name='return_items')
    op.drop_index(op.f('ix_return_items_id'), table_name='return_items')
    op.drop_table('return_items')
    op.drop_index(op.f('ix_refunds_status'), table_name='refunds')
    op.drop_index(op.f('ix_refunds_return_request_id'), table_name='refunds')
    op.drop_index(op.f('ix_refunds_refund_number'), table_name='refunds')
    op.drop_index(op.f('ix_refunds_payment_id'), table_name='refunds')
    op.drop_index(op.f('ix_refunds_id'), table_name='refunds')
    op.drop_table('refunds')
    op.drop_index(op.f('ix_promotion_usages_user_id'), table_name='promotion_usages')
    op.drop_index(op.f('ix_promotion_usages_promotion_id'), table_name='promotion_usages')
    op.drop_index(op.f('ix_promotion_usages_order_id'), table_name='promotion_usages')
    op.drop_index(op.f('ix_promotion_usages_id'), table_name='promotion_usages')
    op.drop_table('promotion_usages')
    op.drop_index(op.f('ix_payment_transactions_transaction_type'), table_name='payment_transactions')
    op.drop_index(op.f('ix_payment_transactions_transaction_status'), table_name='payment_transactions')
    op.drop_index(op.f('ix_payment_transactions_payment_id'), table_name='payment_transactions')
    op.drop_index(op.f('ix_payment_transactions_id'), table_name='payment_transactions')
    op.drop_table('payment_transactions')
    op.drop_index(op.f('ix_order_item_discounts_promotion_id'), table_name='order_item_discounts')
    op.drop_index(op.f('ix_order_item_discounts_order_item_id'), table_name='order_item_discounts')
    op.drop_index(op.f('ix_order_item_discounts_id'), table_name='order_item_discounts')
    op.drop_table('order_item_discounts')
    op.drop_index(op.f('ix_order_allocations_warehouse_id'), table_name='order_allocations')
    op.drop_index(op.f('ix_order_allocations_order_item_id'), table_name='order_allocations')
    op.drop_index(op.f('ix_order_allocations_id'), table_name='order_allocations')
    op.drop_index(op.f('ix_order_allocations_allocation_status'), table_name='order_allocations')
    op.drop_table('order_allocations')
    op.drop_index(op.f('ix_inventory_reservations_reservation_status'), table_name='inventory_reservations')
    op.drop_index(op.f('ix_inventory_reservations_product_variant_id'), table_name='inventory_reservations')
    op.drop_index(op.f('ix_inventory_reservations_order_item_id'), table_name='inventory_reservations')
    op.drop_index(op.f('ix_inventory_reservations_order_id'), table_name='inventory_reservations')
    op.drop_index(op.f('ix_inventory_reservations_id'), table_name='inventory_reservations')
    op.drop_table('inventory_reservations')
    op.drop_index(op.f('ix_image_group_id'), table_name='image_group')
    op.drop_table('image_group')
    op.drop_index(op.f('ix_specification_types_id'), table_name='specification_types')
    op.drop_table('specification_types')
    op.drop_index(op.f('ix_shipments_warehouse_id'), table_name='shipments')
    op.drop_index(op.f('ix_shipments_tracking_number'), table_name='shipments')
    op.drop_index(op.f('ix_shipments_status'), table_name='shipments')
    op.drop_index(op.f('ix_shipments_shipment_number'), table_name='shipments')
    op.drop_index(op.f('ix_shipments_order_id'), table_name='shipments')
    op.drop_index(op.f('ix_shipments_id'), table_name='shipments')
    op.drop_index(op.f('ix_shipments_carrier'), table_name='shipments')
    op.drop_table('shipments')
    op.drop_index(op.f('ix_seo_keywords_id'), table_name='seo_keywords')
    op.drop_table('seo_keywords')
    op.drop_index(op.f('ix_search_keywords_id'), table_name='search_keywords')
    op.drop_table('search_keywords')
    op.drop_index(op.f('ix_reviews_id'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_index(op.f('ix_return_requests_status'), table_name='return_requests')
    op.drop_index(op.f('ix_return_requests_return_number'), table_name='return_requests')
    op.drop_index(op.f('ix_return_requests_order_id'), table_name='return_requests')
    op.drop_index(op.f('ix_return_requests_id'), table_name='return_requests')
    op.drop_index(op.f('ix_return_requests_customer_id'), table_name='return_requests')
    op.drop_table('return_requests')
    op.drop_index(op.f('ix_related_products_id'), table_name='related_products')
    op.drop_table('related_products')
    op.drop_index(op.f('ix_questions_id'), table_name='questions')
    op.drop_table('questions')
    op.drop_index(op.f('ix_promotion_targets_promotion_id'), table_name='promotion_targets')
    op.drop_index(op.f('ix_promotion_targets_id'), table_name='promotion_targets')
    op.drop_table('promotion_targets')
    op.drop_index(op.f('ix_promotion_rules_promotion_id'), table_name='promotion_rules')
    op.drop_index(op.f('ix_promotion_rules_id'), table_name='promotion_rules')
    op.drop_table('promotion_rules')
    op.drop_index(op.f('ix_promotion_coupons_id'), table_name='promotion_coupons')
    op.drop_index('ix_promotion_coupon_status', table_name='promotion_coupons')
    op.drop_index('ix_promotion_coupon_promotion', table_name='promotion_coupons')
    op.drop_index('ix_promotion_coupon_code', table_name='promotion_coupons')
    op.drop_table('promotion_coupons')
    op.drop_index(op.f('ix_promotion_actions_id'), table_name='promotion_actions')
    op.drop_index('ix_promotion_action_reward_type', table_name='promotion_actions')
    op.drop_index('ix_promotion_action_promotion', table_name='promotion_actions')
    op.drop_table('promotion_actions')
    op.drop_index(op.f('ix_product_videos_id'), table_name='product_videos')
    op.drop_table('product_videos')
    op.drop_table('product_variants')
    op.drop_index(op.f('ix_product_tags_id'), table_name='product_tags')
    op.drop_table('product_tags')
    op.drop_index(op.f('ix_product_seo_id'), table_name='product_seo')
    op.drop_table('product_seo')
    op.drop_index(op.f('ix_product_badges_id'), table_name='product_badges')
    op.drop_table('product_badges')
    op.drop_index(op.f('ix_payments_payment_provider'), table_name='payments')
    op.drop_index(op.f('ix_payments_payment_method'), table_name='payments')
    op.drop_index(op.f('ix_payments_order_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_order_timelines_order_id'), table_name='order_timelines')
    op.drop_index(op.f('ix_order_timelines_id'), table_name='order_timelines')
    op.drop_index(op.f('ix_order_timelines_event'), table_name='order_timelines')
    op.drop_table('order_timelines')
    op.drop_index(op.f('ix_order_notifications_status'), table_name='order_notifications')
    op.drop_index(op.f('ix_order_notifications_order_id'), table_name='order_notifications')
    op.drop_index(op.f('ix_order_notifications_notification_type'), table_name='order_notifications')
    op.drop_index(op.f('ix_order_notifications_id'), table_name='order_notifications')
    op.drop_table('order_notifications')
    op.drop_index(op.f('ix_order_notes_order_id'), table_name='order_notes')
    op.drop_index(op.f('ix_order_notes_note_type'), table_name='order_notes')
    op.drop_index(op.f('ix_order_notes_id'), table_name='order_notes')
    op.drop_index(op.f('ix_order_notes_created_by'), table_name='order_notes')
    op.drop_table('order_notes')
    op.drop_index(op.f('ix_order_items_id'), table_name='order_items')
    op.drop_table('order_items')
    op.drop_index(op.f('ix_order_discounts_promotion_id'), table_name='order_discounts')
    op.drop_index(op.f('ix_order_discounts_order_id'), table_name='order_discounts')
    op.drop_index(op.f('ix_order_discounts_id'), table_name='order_discounts')
    op.drop_index(op.f('ix_order_discounts_coupon_code'), table_name='order_discounts')
    op.drop_table('order_discounts')
    op.drop_index(op.f('ix_invoices_status'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_order_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_invoice_number'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_id'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_inventory_summaries_id'), table_name='inventory_summaries')
    op.drop_table('inventory_summaries')
    op.drop_index(op.f('ix_descriptions_id'), table_name='descriptions')
    op.drop_table('descriptions')
    op.drop_index(op.f('ix_delivery_details_id'), table_name='delivery_details')
    op.drop_table('delivery_details')
    op.drop_table('compare_items')
    op.drop_index(op.f('ix_cart_items_id'), table_name='cart_items')
    op.drop_table('cart_items')
    op.drop_index(op.f('ix_user_sessions_id'), table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_index(op.f('ix_shipping_rates_zone_id'), table_name='shipping_rates')
    op.drop_index(op.f('ix_shipping_rates_shipping_method'), table_name='shipping_rates')
    op.drop_index(op.f('ix_shipping_rates_name'), table_name='shipping_rates')
    op.drop_index(op.f('ix_shipping_rates_id'), table_name='shipping_rates')
    op.drop_index(op.f('ix_shipping_rates_carrier'), table_name='shipping_rates')
    op.drop_table('shipping_rates')
    op.drop_index(op.f('ix_promotions_status'), table_name='promotions')
    op.drop_index(op.f('ix_promotions_id'), table_name='promotions')
    op.drop_index(op.f('ix_promotions_code'), table_name='promotions')
    op.drop_table('promotions')
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_order_number'), table_name='orders')
    op.drop_index(op.f('ix_orders_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_fulfillment_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_customer_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_order_addresses_id'), table_name='order_addresses')
    op.drop_table('order_addresses')
    op.drop_index(op.f('ix_carts_id'), table_name='carts')
    op.drop_table('carts')
    op.drop_index(op.f('ix_warehouses_warehouse_code'), table_name='warehouses')
    op.drop_index(op.f('ix_warehouses_id'), table_name='warehouses')
    op.drop_table('warehouses')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tags_id'), table_name='tags')
    op.drop_table('tags')
    op.drop_index(op.f('ix_shipping_zones_zone_name'), table_name='shipping_zones')
    op.drop_index(op.f('ix_shipping_zones_zone_code'), table_name='shipping_zones')
    op.drop_index(op.f('ix_shipping_zones_id'), table_name='shipping_zones')
    op.drop_table('shipping_zones')
    op.drop_index(op.f('ix_promotion_types_id'), table_name='promotion_types')
    op.drop_table('promotion_types')
    op.drop_index(op.f('ix_categories_id'), table_name='categories')
    op.drop_table('categories')
    op.drop_index(op.f('ix_brands_id'), table_name='brands')
    op.drop_table('brands')
    op.drop_index(op.f('ix_badges_id'), table_name='badges')
    op.drop_table('badges')
    # ### end Alembic commands ###
